# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box_url = "file://../ansible/centos7.box"

  config.vm.define "local" do |web|
    web.vm.box = "web"
    web.vm.network :forwarded_port, guest: 22, host: 11011
    web.vm.network "public_network", ip: "192.168.10.101"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

end
