
- name: del mariadb
  yum: name=mariadb-libs state=absent

- name: mysql 5.7(リポジトリ)
  yum: name={{ item }} state=present
  with_items:
    - http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm


- name: mysql 5.7
  yum: name={{ item }} state=present
  with_items:
    - mysql-community-server
    - mysql-community-devel
    - mysql-community-libs-compat

# なぜか使えない。何故だ。
#- name: 設定の修正
#  lineinfile: dest='/etc/my.cnf' state=present regexp="{{ item.regexp }}" line="{{ item.line }}"
#  with_items:
#    - { regexp: '^default_password_lifetime=',    line: 'default_password_lifetime=0' }
#    - { regexp: '^validate_password_policy=',    line: 'validate_password_policy=LOW' }  # ※ ローカル開発専用のときのみ利用すること
#    - { regexp: '^validate_password=',    line: 'validate_password=OFF' }  # ※ ローカル開発専用のときのみ利用すること

- name: mysql設定
  shell: systemctl enable mysqld.service

- name: mysql（再）起動
  shell: systemctl restart mysqld.service

# パスワードが/var/log/mysqld.logに書かれているという強烈な仕様。
# mysqlのrootパスワードが毎回変わるため自動では厳しい。とりあえずログインしてから以下のSQLを打つ。（ローカル開発環境なら）
#SET PASSWORD= 'Do_you_love_MySQL57';
#CREATE USER 'root'@'%' IDENTIFIED WITH mysql_native_password AS 'password';
#SET PASSWORD FOR root = PASSWORD('password');
#GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
