# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box_url = "file://../ansible/centos64-x86_64-20140116.box"

  config.vm.box = "test"
  config.vm.network :forwarded_port, guest: 22, host: 11015
  config.vm.network "public_network", ip: "192.168.10.105"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
end
