# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box_url = "file://../ansible/centos64-x86_64-20140116.box"

  config.vm.define "local-web" do |web|
    web.vm.box = "web"
    web.vm.network :forwarded_port, guest: 22, host: 11011
    web.vm.network "public_network", ip: "192.168.10.101"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "local-db" do |db|
    db.vm.box = "db"

    db.vm.network :forwarded_port, guest: 22, host: 11012
    db.vm.network "public_network", ip: "192.168.10.102"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "development-web" do |web|
    web.vm.box = "web"
    web.vm.network :forwarded_port, guest: 22, host: 11013
    web.vm.network "public_network", ip: "192.168.10.103"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "development-db" do |db|
    db.vm.box = "db"
    db.vm.network :forwarded_port, guest: 22, host: 11014
    db.vm.network "public_network", ip: "192.168.10.104"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

end
