# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ansible"
  config.vm.box_url = "./centos7.box"

  # Ansibleのファイルを同期させるときはinventoryに実行権限がついていてはいけないので権限設定がMUST
  config.vm.synced_folder "C:/github/personal/Ansible", "/home/vagrant/Ansible", :mount_options => ['dmode=775', 'fmode=664']
  config.vm.network :forwarded_port, guest: 22, host: 11010
  config.vm.network "public_network", ip: "192.168.10.100"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

end
